#cloud-config
package_update: true
package_upgrade: true
fqdn: cold_machnine.local
packages:
  - sshfs
  - build-essential
  - git
  - snapcraft
  - autoconf
  - automake
  - curl
  - elinks
  - wget
  - tmux
  - tree
  - htop
  - lynx
  - pandoc
  - rsync
  - libexpat1
  - apache2
  - apache2-utils
  - ssl-cert
  - libapache2-mod-wsgi
  - makepasswd
  - shellcheck
groups:
  - staff
  - www-data
snap:
  commands:
  - [ install, --classic, go ]
  - [ install, --clasic, deno ]
  - [ install, datatools ]
  - [ install, dataset ]
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
